
sudo: required
services:
- docker
language: bash
script:
#general settings
- >
  OWNER=valentinvieriu
  IMAGE_NAME=alpine-qemu
  QNAME=$OWNER/$IMAGE_NAME
  QUEMU_VERSION=2.12.0
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# get qemu-arm-static binary
- mkdir tmp
- >
  pushd tmp &&
  curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v${QUEMU_VERSION}/qemu-arm-static.tar.gz &&
  tar xzf qemu-arm-static.tar.gz &&
  popd
# build image
- docker build -t $QNAME:build .
# test image
- docker run $QNAME:build uname -a
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ]; then
    echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
    export TAG_SHORT=$(grep "FROM " Dockerfile | sed 's/.*://')
    export TAG_LONG=$(grep "FROM " Dockerfile | sed 's/.*://')-${QUEMU_VERSION}
    docker tag $QNAME:build $QNAME:$TAG_SHORT
    docker tag $QNAME:build $QNAME:$TAG_LONG
    docker tag $QNAME:build $QNAME:latest
    docker push $QNAME:$TAG_SHORT
    docker push $QNAME:$TAG_LONG
    docker push $QNAME:latest
  fi
